version: "3.7"

services:
  gateway:
    build:
      context: ./gateway

  frontend:
    build:
      context: ./frontend
    environment:
      SPA_DEFAULT_LOCALE: "es"

  backend:
    build:
      context: .
