# This file is intended as an override to build the backend using the local m2 repo
version: "3.7"

services:
  gateway:
    build:
      context: ./gateway
    volumes:
      - "./nginx-no-csp.conf:/etc/nginx/nginx.conf"

  frontend:
    build:
      context: ./frontend

  backend:
    build:
      context: .
    volumes:
      - ~/.m2:/root/.m2
