name: Build and Validate Configuration

on:
  pull_request:
    branches: [main]

  push:
    branches-ignore: [main, 2.x, 2.3.x, 2.6.x]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          java: [ '8' ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - name: Build and Test
        run: mvn --batch-mode --update-snapshots clean package
