name: Run UI tests on FirefoxInGithubActions
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      firefox:
        image: selenium/node-firefox:3.141.59-gold
        env:
          HUB_HOST: hub
          HUB_PORT: 4444
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Checkout ui test framework
        uses: actions/checkout@master
        with:
          repository: openmrs/openmrs-contrib-uitestframework
      - name: Build ui test framework
        run: mvn clean install -B
      - name: Checkout distro/uitests
        uses: actions/checkout@master
        with:
          repository: openmrs/openmrs-distro-referenceapplication
      - name: Build distro/uitests
        run: |
          cd ui-tests
          cp -f src/test/resources/org/openmrs/uitestframework/test-ci.properties src/test/resources/org/openmrs/uitestframework/test.properties
          mvn clean install -B -DskipTests=false
