
name: CI
on:
  release:
    types: [published]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: IsantePlus/docker-isanteplus-server
  USERNAME: ${{ secrets.RELEASE_USERNAME }}
  TOKEN: ${{ secrets.RELEASE_TOKEN }}
  ISANTEPLUS_VERSION: ${{ github.head_ref }}

jobs:
  build-test-publish:
    name: Build, Test, and Publish iSantePlus Image
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Test Tag
        run: |
           echo "${{ github.base_ref }} | ${{ github.head_ref }} | ${{ github.ref }} | ${{ github.event.branch }}"
    
      - name: Checkout IsantePlus/docker-isanteplus-db
        uses: actions/checkout@v2
        with:
          repository: IsantePlus/docker-isanteplus-db
          ref: ci
          clean: false
      - name: Build Test Db Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          load: true
          build-args: |
            ISANTEPLUS_VERSION=${{ github.head_ref }}
            USERNAME=${{ secrets.RELEASE_USERNAME }}
            TOKEN=${{ secrets.RELEASE_TOKEN }}
          tags: isanteplus/isanteplus-db:test
          cache-from: type=registry,ref= ${{ steps.meta.outputs.tags }}
          cache-to: type=inline
    
      - name: Checkout IsantePlus/docker-isanteplus-server
        uses: actions/checkout@v2
        with:
          repository: IsantePlus/docker-isanteplus-server
          ref: ci
          clean: false
      - name: Build Test Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          load: true
          build-args: |
            ISANTEPLUS_VERSION=${{ github.head_ref }}
            USERNAME=${{ secrets.RELEASE_USERNAME }}
            TOKEN=${{ secrets.RELEASE_TOKEN }}
          tags: isanteplus/isanteplus-server:test
          cache-from: type=registry,ref= ${{ steps.meta.outputs.tags }}
          cache-to: type=inline
      - name: Start up iSantePlus Containers
        run: docker-compose -f ci.docker-compose.yaml up -d
      - name: Sleep for 5 minutes
        run: sleep 5m
        shell: bash
      - name: Check containers
        run: docker ps
      - name: Check containers logs
        run: docker logs isanteplus  
      - name: wait for openmrs instance to start
        run: while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:8080/openmrs/login.htm)" != "200" ]]; do sleep 1; done
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Checkout IsantePlus/isanteplus-qaframework
        uses: actions/checkout@v2
        with:
          repository: IsantePlus/isanteplus-qaframework
          ref : main
      - name: Run isanteplus QA Tests
        run: |
          echo "cucumber.publish.enabled=true" > src/test/resources/cucumber.properties
          mvn clean install -DskipTests=true
          cp -f src/test/resources/test-local.properties src/test/resources/test.properties
          mvn test
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Docker image
        uses: docker/build-push-action@v2
        with:
          image: isanteplus/isanteplus-server:test
          push: true
          build-args: |
            ISANTEPLUS_VERSION=${{ github.event.ref }}
            USERNAME=${{ secrets.RELEASE_USERNAME }}
            TOKEN=${{ secrets.RELEASE_TOKEN }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ steps.meta.outputs.tags }}
          cache-to: type=inline
